(in-package :clutter)

(def-suite primitives :in clutter)

(in-suite primitives)

(test bool-true)
(test bool-false)
(test null)
(test define-function-initially)
(test defprimitive)

(test prim/not)
(test prim/null?)
(test prim/cons)
(test prim/head)
(test prim/tail)
(test prim/set-head)
(test prim/set-tail)
(test prim/eql?)
(test prim/symbol?)
(test prim/number?)
(test prim/<?)
(test prim/>?)
(test prim/=?)
(test prim/+)
(test prim/-)
(test prim/*)
(test prim//)
(test prim/apply)
(test prim/call)
(test prim/print)
